name: flow_basic

on: 
   label: 
       types: [ created, edited ]

jobs:
    name: job1
      runs-on: ubuntu-latest

      steps:
      - name: print a greeting
        env:
            my_var: my name is
            first_name: mona
            last_name: octocat
        run: |
           echo $my_var $first_name $last_name.

    name: job2
    needs: job1
      runs-on: ubuntu-latest

      steps:
      - name: second job run
        env:
            done: finished
        run: echo $done




