name: "docker setup"

on:
  push:
   branches: master

jobs:
   hello_world_job:
      runs-on: ubuntu-latest
      name: 'job to say hello'
      steps:
          - name: "hello world action"
            id: hello
            uses: actions/hello-world-docker-action@v1
            with:
               who-to-greet: 'mona the octocat'

          - name: "get the output time"
            run: echo "the time is ${{ steps.hello.outputs.time }}"
