name: Pylint

on:
  push:
    branches:
      - tmp_mytest

jobs:
  job_1:
     build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
             python -m pip install --upgrade pip
             pip install pylint
        - name: Analysing the code with pylint
          run: |
             pylint `ls -R|grep .py$|xargs`
 
   job_2:
      
      on: [push]
   
      name: run job2
         needs: job_1
    
      runs-on: ubuntu-latest
      steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.  
