name: super-linter

on: push


jobs:
    super-lint:
       name: lint code base
       runs-on: ubuntu-latest

       steps:
           - name: checkout code
             uses: actions/checkout@2

           - name: run super-linter
             uses: github/super-linter@3
             env:
                DEFAULT_BRANCH: tmp_mytest
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
