name: 'Example'
description: 'Receives file and generates output'
inputs:
  file-path: . 
    description: "Path to test script"
    required: true
    default: 'tst.txt'
outputs:
  results-file: test-complete.txt 
    description: "Path to results file"
