name: play_with_output

on: ['pull']

jobs:

    run-on: ubuntu-latest
    steps:

        # check out repository
        - uses: actions/checkout@v2

        # test the new workflow
        - uses: ./.github/actions/test_output 

        # run the python script
        - run: python work1.py

    outputs:
        results-file: 
        description: "path to results file"
